### ISSUE TITLE
A lot of compile errors

### ISSUE THREAD

**Issue by bertdeelman** [1mckenna/esp32_iGrill#19]
Hi,

First thanks for your great work! Really nice. 
 
I followed the clear instructions and add the Arduino libraries. But I receive a lot of compile errors about redefining. 

Is there a solution for this? It was mentioned before but that topic was closed. 

Regards,
Bert

**Comment by GerbenBakker** [comment]
Hi Bert, 

I also had some errors; solved it by adding the exact version of the libraries as in the guidance.  (initially added newest versions)

With the somewhat older libraries, it worked perfectly 

Regards

**Comment by bertdeelman** [comment]
Hi Gerben,

I made some progress. It seems to be that the LITTLEFS library is now part of the core Arduino. I use the IDE v1.8.19 macOS version. So there is no need to add that library to the sketch. LITTLEFS is renamed to LittleFS. After those changes I can upload it to ESP32 board. It starts, portal ok, WiFi Ok. But some weird error message after Performing iGrill App Authentication. Guru Meditation Error: Core  0 panic'ed (Double exception). 

I need to figure out what is happening here and if I can debug. 

Groet,
Bert

**Comment by GerbenBakker** [comment]
Hi Bert, I recall having the same/similar issue. Not too much of an arduino expert myself so I will not be able to guide you any further than sharing that by including the exact library versions (including ESP board) i was able to compile the code without any modification. My ealier attempt to chage LITTLEFS to LittleFS resulted in same error that you currently have over the serial interface. Happy to send you my compiled binary (for DFRobot FireBeetle ESP8266 IoT Development Board - Wi-Fi - ).

**Comment by 0711smarthome** [comment]
I have this fault  if i compile

'custom_MQTT_SERVER_LEN' was not declared in this scope

**Comment by 0711smarthome** [comment]
Is it possible that someone send me the bin file?

**Comment by Simeonn67** [comment]
Hi westado.
Got the same issue but it worked for me after adding:
#include "config.h"

You may have to move the file ;)

Hope this will work for you too

**Comment by GerbenBakker** [comment]
> Is it possible that someone send me the bin file?
[esp32_iGrill.ino.esp32.zip](https://github.com/1mckenna/esp32_iGrill/files/8995556/esp32_iGrill.ino.esp32.zip)
Hope this helps

**Comment by 0711smarthome** [comment]
> > Is it possible that someone send me the bin file?
> > [esp32_iGrill.ino.esp32.zip](https://github.com/1mckenna/esp32_iGrill/files/8995556/esp32_iGrill.ino.esp32.zip)
> > Hope this helps

Thanks it works!!

**Comment by 1mckenna** [comment]
Sorry for the delayed response, but this should be fixed now. I've tested and confirmed it working on my end using the latest versions of all the libraries and the built in littlefs library (I updated the README to list the versions i tested with).

Can you try again and let me know if it resolves your issue?

**Comment by andreq** [comment]
Not the OP, but tried with latest libraries and latest code, seem to be all good. 
Also seem to fix the random case where my esp32 would just decide to go offline after a while 👍

**Comment by 1mckenna** [comment]
Thanks for testing and letting me know it worked for you as well. I am going to go ahead and close this issue now.

**Comment by bjhiltbrand** [comment]
This is not working in my instance. I have installed all dependencies using the versions listed in the Readme, yet I still get the following error when attempting to compile:

C:\Workspaces\esp32_iGrill\esp32_iGrill.ino:35:105: fatal error: LittleFS.h: No such file or directory

Edit to add using the binary file shared above and flashing with esptool, the ESP32 seems to be working. Just compiling from source is giving me issues.
